### ISSUE TITLE
Calling `configure` breaks everything

### ISSUE THREAD

**Issue by cjbottaro** [Rykian/clockwork#16]
Hi.

This code doesn't work:

```ruby
module Clockwork

  configure do |config|
    config[:sleep_timeout] = 1
    config[:logger] = Logger.new(STDOUT)
    config[:tz] = "CST"
    config[:max_threads] = 10
    config[:thread] = true
  end

  handler { |job| puts job.inspect }

  every(1.second, "frequent_hob")
end
```

But if you comment out the configure block, then everything runs fine.

Thanks.

**Comment by jwoertink** [comment]
I'm getting the same after upgrading to 2.0
```
NoMethodError: undefined method `configure' for Clockwork:Module
```
